// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Add: typeof import('./components/Add/Index.vue')['default']
    AddTask: typeof import('./components/Add/Task.vue')['default']
    Aside: typeof import('./components/Aside.vue')['default']
    AtomsButton: typeof import('./components/Atoms/Button/Index.vue')['default']
    AtomsHeader: typeof import('./components/Atoms/Header/Index.vue')['default']
    AtomsHeadline: typeof import('./components/Atoms/Headline/Index.vue')['default']
    AtomsIcons: typeof import('./components/Atoms/Icons/Index.vue')['default']
    Button: typeof import('./components/Button/Index.vue')['default']
    Card: typeof import('./components/Card/Index.vue')['default']
    Droppable: typeof import('./components/Droppable/Index.vue')['default']
    Extendedlink: typeof import('./components/extendedlink/Index.vue')['default']
    ExtendedLink: typeof import('./components/ExtendedLink/Index.vue')['default']
    Filter: typeof import('./components/Filter/Index.vue')['default']
    Form: typeof import('./components/Form/Index.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Headline: typeof import('./components/Headline/Index.vue')['default']
    Icons: typeof import('./components/Icons/Index.vue')['default']
    Input: typeof import('./components/Input/Index.vue')['default']
    List: typeof import('./components/List/Index.vue')['default']
    ListItem: typeof import('./components/List/Item.vue')['default']
    Loader: typeof import('./components/Loader/Index.vue')['default']
    Modal: typeof import('./components/Modal/Index.vue')['default']
    MoleculesFilter: typeof import('./components/Molecules/Filter/Index.vue')['default']
    PropertyEditor: typeof import('./components/PropertyEditor/Index.vue')['default']
    PropertyEditorLayerEditor: typeof import('./components/PropertyEditor/LayerEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stat: typeof import('./components/Stat/Index.vue')['default']
    Tag: typeof import('./components/Tag/Index.vue')['default']
    TagsList: typeof import('./components/TagsList/Index.vue')['default']
    Toaster: typeof import('./components/Toaster/Index.vue')['default']
    UserInfo: typeof import('./components/UserInfo/Index.vue')['default']
    VisualEditor: typeof import('./components/VisualEditor/Index.vue')['default']
    VisualEditorAdd: typeof import('./components/VisualEditor/Add.vue')['default']
    VisualEditorAddLayer: typeof import('./components/VisualEditor/AddLayer.vue')['default']
    VisualEditorLayer: typeof import('./components/VisualEditor/Layer.vue')['default']
    VisualEditorLayerEditor: typeof import('./components/VisualEditor/LayerEditor.vue')['default']
  }
}
